// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "e6fdd4fe6858e33dd1f1ceb67d110a11104c8c18f4aeb08026290831683d0de2")
